image: cgr.dev/chainguard/node:latest-dev

stages:
  - build
  - deploy
variables:
  COSIGN_YES: "true"
  REKOR_URL: "https://rekor.sigstage.dev"
  FULCIO_URL: "https://fulcio.sigstage.dev"
  OIDC_ISSUER_URL: "https://oauth2.sigstage.dev/auth"

include:
  - local: 'npm.gitlab-ci.yml'

npm-provenance-example:
  stage: build
  # Set the JWT token audience and the name of the env variable
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: "sigstore"

  script:
    - echo "git clone" && git clone -b gitlab-provenance https://github.com/wlynch/npm-cli.git
    - echo "npm install" && cd npm-cli && npm install -g

set-deploy:
  stage: deploy
  # Set the JWT token audience and the name of the env variable
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: "sigstore"

  script:
    - echo "Running NPM publish"